export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const GET_ONE_TRAINEES_ALL_DETAILS = "GET_ONE_TRAINEES_ALL_DETAILS";
export const GET_TRAINEE = "GET_TRAINEE";
export const CREATE_TRAINEES = "CREATE_TRAINEES";
export const GET_CYCLES = "GET_CYCLES";
export const CREATE_CYCLES = "CREATE_CYCLES";
export const UPDATE_CYCLE = "UPDATE_CYCLE";
export const DELETE_CYCLE = "DELETE_CYCLE";
export const CREATE_CYCLE_ERROR = "CREATE_CYCLE_ERROR";
export const UPDATE_CYCLE_ERROR = "UPDATE_CYCLE_ERROR";
export const DELETE_CYCLE_ERROR = "DELETE_CYCLE_ERROR";
export const GET_SOFT_DELETED_TRAINEES = "GET_SOFT_DELETED_TRAINEES";
export const GET_SOFT_DELETED_TRAINEES_ERROR =
  "GET_SOFT_DELETED_TRAINEES_ERROR";
export const GET_ALL_FILTERED_TRAINEES = "GET_ALL_FILTERED_TRAINEES";
export const LOAD_DATA_INTO_DB_REQUEST = "LOAD_DATA_INTO_DB_REQUEST";
export const LOAD_DATA_INTO_DB_SUCCESS = "LOAD_DATA_INTO_DB_SUCCESS";
export const LOAD_DATA_INTO_DB_FAIL = "LOAD_DATA_INTO_DB_FAIL";
export const RESEND_MAPPED_DATA_INTO_DB = "RESEND_MAPPED_DATA_INTO_DB";
export const GET_TRAINEE_TO_UPDATE = "GET_TRAINEE_TO_UPDATE";
export const GET_TRAINEE_TO_UPDATE_FAIL = "GET_TRAINEE_TO_UPDATE_FAIL";
export const UPDATE_TRAINEE = "UPDATE_TRAINEE";
export const UPDATE_TRAINEE_FAIL = "UPDATE_TRAINEE_FAIL";
export const UPDATE_TRAINEE_ATTRIBUTE = "UPDATE_TRAINEE_ATTRIBUTE";
export const UPDATE_TRAINEE_ATTRIBUTE_FAIL = "UPDATE_TRAINEE_ATTRIBUTE_FAIL";
export const EMPTYING_TRASH = "EMPTYING_TRASH";
export const GET_ONE_TRAINEE_SCORE = "GET_ONE_TRAINEE_SCORE";
export const UPDATE_TRAINEE_SCORE = "UPDATE_TRAINEE_SCORE";
export const CREATE_TRAINEE_SCORE = "CREATE_TRAINEE_SCORE";
export const GET_SCORE_TYPES = "GET_SCORE_TYPES";
export const CREATE_SCORE_TYPE = "CREATE_SCORE_TYPE";
export const CREATE_SCORE_ERROR = "CREATE_SCORE_ERROR";
export const GET_ONE_SCORE_TYPE = "GET_ONE_SCORE_TYPE";
export const GET_SCORE_VALUES = "GET_SCORE_VALUES";
export const CREATE_SCORE_VALUES = "CREATE_SCORE_VALUES";
export const CREATE_SCORE_VALUE_ERROR = "CREATE_SCORE_VALUE_ERROR";
export const DELETE_SCORE_TYPE = "DELETE_SCORE_TYPE";
export const DELETE_SCORE_ERROR = "DELETE_SCORE_ERROR";
export const UPDATE_SCORE_TYPE = "UPDATE_SCORE_TYPE";
export const UPDATE_SCORE_ERROR = "UPDATE_SCORE_ERROR";
export const UPDATE_SCORE_VALUE = "UPDATE_SCORE_VALUE";
export const UPDATE_SCORE_VALUE_ERROR = "UPDATE_SCORE_VALUE_ERROR";
export const DELETE_SCORE_VALUE = "DELETE_SCORE_VALUE";
export const DELETE_SCORE_VALUE_ERROR = "DELETE_SCORE_VALUE_ERROR";
export const UPDATE_MANY_SCORE_VALUES = "UPDATE_MANY_SCORE_VALUES";
export const UPDATE_TRAINEE_STATUS_FAIL = "UPDATE_TRAINEE_STATUS_FAIL";
export const UPDATE_TRAINEE_STATUS = "UPDATE_TRAINEE_STATUS";
export const FETCH_TRAINEE ="FETCH_TRAINEE";




