export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const FETCH_TRAINEE ="FETCH_TRAINEE";
export const GET_TRAINEE = "GET_TRAINEE";
export const CREATE_TRAINEES = "CREATE_TRAINEES";
export const GET_CYCLES = "GET_CYCLES";
export const CREATE_CYCLES = "CREATE_CYCLES";
export const UPDATE_CYCLE = "UPDATE_CYCLE";
export const DELETE_CYCLE = "DELETE_CYCLE";
export const CREATE_CYCLE_ERROR = "CREATE_CYCLE_ERROR";
export const UPDATE_CYCLE_ERROR = "UPDATE_CYCLE_ERROR";
export const DELETE_CYCLE_ERROR = "DELETE_CYCLE_ERROR";
export const GET_SOFT_DELETED_TRAINEES = "GET_SOFT_DELETED_TRAINEES";
export const GET_SOFT_DELETED_TRAINEES_ERROR =
  "GET_SOFT_DELETED_TRAINEES_ERROR";
export const GET_ALL_FILTERED_TRAINEES = "GET_ALL_FILTERED_TRAINEES";
export const EMPTYING_TRASH = "EMPTYING_TRASH"