export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const GET_ONE_TRAINEES_ALL_DETAILS = "GET_ONE_TRAINEES_ALL_DETAILS";
export const GET_TRAINEE = "GET_TRAINEE";
export const SET_TRAINEE = "SET_TRAINEE";
export const CREATE_TRAINEES = "CREATE_TRAINEES";
export const GET_CYCLES = "GET_CYCLES";
export const CREATE_CYCLES = "CREATE_CYCLES";
export const UPDATE_CYCLE = "UPDATE_CYCLE";
export const DELETE_CYCLE = "DELETE_CYCLE";
export const CREATE_CYCLE_ERROR = "CREATE_CYCLE_ERROR";
export const UPDATE_CYCLE_ERROR = "UPDATE_CYCLE_ERROR";
export const DELETE_CYCLE_ERROR = "DELETE_CYCLE_ERROR";
export const GET_SOFT_DELETED_TRAINEES = "GET_SOFT_DELETED_TRAINEES";
export const GET_SOFT_DELETED_TRAINEES_ERROR =
  "GET_SOFT_DELETED_TRAINEES_ERROR";
export const GET_ALL_FILTERED_TRAINEES = "GET_ALL_FILTERED_TRAINEES";
export const GET_ALL_FILTERED_PROGRAMS = "GET_ALL_FILTERED_PROGRAMS";
export const GET_ALL_FILTERED_JOB_POST = "GET_ALL_FILTERED_JOB_POST";
export const GET_ALL_FILTERED_ROLES_ACCESS = "GET_ALL_FILTERED_ROLES_ACCESS";
export const LOAD_DATA_INTO_DB_REQUEST = "LOAD_DATA_INTO_DB_REQUEST";
export const LOAD_DATA_INTO_DB_SUCCESS = "LOAD_DATA_INTO_DB_SUCCESS";
export const LOAD_DATA_INTO_DB_FAIL = "LOAD_DATA_INTO_DB_FAIL";
export const RESEND_MAPPED_DATA_INTO_DB = "RESEND_MAPPED_DATA_INTO_DB";
export const GET_TRAINEE_TO_UPDATE = "GET_TRAINEE_TO_UPDATE";
export const GET_TRAINEE_TO_UPDATE_FAIL = "GET_TRAINEE_TO_UPDATE_FAIL";
export const UPDATE_TRAINEE = "UPDATE_TRAINEE";
export const UPDATE_TRAINEE_FAIL = "UPDATE_TRAINEE_FAIL";
export const UPDATE_TRAINEE_ATTRIBUTE = "UPDATE_TRAINEE_ATTRIBUTE";
export const UPDATE_TRAINEE_ATTRIBUTE_FAIL = "UPDATE_TRAINEE_ATTRIBUTE_FAIL";
export const EMPTYING_TRASH = "EMPTYING_TRASH";
export const GET_ONE_TRAINEE_SCORE = "GET_ONE_TRAINEE_SCORE";
export const UPDATE_TRAINEE_SCORE = "UPDATE_TRAINEE_SCORE";
export const CREATE_TRAINEE_SCORE = "CREATE_TRAINEE_SCORE";
export const GET_SCORE_TYPES = "GET_SCORE_TYPES";
export const CREATE_SCORE_TYPE = "CREATE_SCORE_TYPE";
export const CREATE_SCORE_ERROR = "CREATE_SCORE_ERROR";
export const GET_ONE_SCORE_TYPE = "GET_ONE_SCORE_TYPE";
export const GET_SCORE_VALUES = "GET_SCORE_VALUES";
export const CREATE_SCORE_VALUES = "CREATE_SCORE_VALUES";
export const CREATE_SCORE_VALUE_ERROR = "CREATE_SCORE_VALUE_ERROR";
export const DELETE_SCORE_TYPE = "DELETE_SCORE_TYPE";
export const DELETE_SCORE_ERROR = "DELETE_SCORE_ERROR";
export const UPDATE_SCORE_TYPE = "UPDATE_SCORE_TYPE";
export const UPDATE_SCORE_ERROR = "UPDATE_SCORE_ERROR";
export const UPDATE_SCORE_VALUE = "UPDATE_SCORE_VALUE";
export const UPDATE_SCORE_VALUE_ERROR = "UPDATE_SCORE_VALUE_ERROR";
export const DELETE_SCORE_VALUE = "DELETE_SCORE_VALUE";
export const DELETE_SCORE_VALUE_ERROR = "DELETE_SCORE_VALUE_ERROR";
export const UPDATE_MANY_SCORE_VALUES = "UPDATE_MANY_SCORE_VALUES";
export const UPDATE_TRAINEE_STATUS_FAIL = "UPDATE_TRAINEE_STATUS_FAIL";
export const UPDATE_TRAINEE_STATUS = "UPDATE_TRAINEE_STATUS";
export const LOGIN_USER = "LOGIN_USER";
export const SEND_EMAIL = "SEND_EMAIL";
export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR";
export const MY_APPLICATIONS = "MY_APPLICATIONS";
export const GET_PROGRAMS = "GET_PROGRAMS";
export const GET_COHORTS = "GET_COHORTS";
export const GET_TRAINEE_COHORT = "GET__TRAINEE_COHORT";
export const CREATE_COHORT_SUCCESS = "CREATE_COHORT_SUCCESS";
export const CREATE_COHORT_ERROR = "CREATE_COHORT_ERROR";
export const GET_ONE_JOB_POST_ALL_DETAILS = "GET_ONE_JOB_POST_ALL_DETAILS";
export const GET_TRAINEE_ATTENDANCE = "GET_TRAINEE_ATTENDANCE";
export const GET_TRAINEE_PERFORMANCE = "GET_TRAINEE_PERFORMANCE";
export const SINGLE_USER = "SINGLE_USER";
export const SINGLE_USER_FAIL = "SINGLE_USER_FAIL";
export const USER_TO_UPDATE = "USER_TO_UPDATE";
export const USER_TO_UPDATE_FAIL = "USER_TO_UPDATE_FAIL";
export const CREATE_TRAINEE_APPLICANT_SUCCESS =
  "CREATE_TRAINEE_APPLICANT_SUCCESS";
export const CREATE_TRAINEE_APPLICANT_ERROR = "CREATE_TRAINEE_APPLICANT_ERROR";
export const FETCH_TRAINEES_REQUEST = "FETCH_TRAINEES_REQUEST";
export const FETCH_TRAINEES_SUCCESS = "FETCH_TRAINEES_SUCCESS";
export const SET_CURRENT_TRAINEE_ID = "SET_CURRENT_TRAINEE_ID";
export const FETCH_TRAINEES_FAILURE = "FETCH_TRAINEES_FAILURE";
export const UPDATE_TRAINEE_REQUEST = "UPDATE_TRAINEE_REQUEST";
export const UPDATE_TRAINEE_SUCCESS = "UPDATE_TRAINEE_SUCCESS";
export const UPDATE_TRAINEE_FAILURE = "UPDATE_TRAINEE_FAILURE";
export const DELETE_TRAINEE_REQUEST = "DELETE_TRAINEE_REQUEST";
export const DELETE_TRAINEE_SUCCESS = " DELETE_TRAINEE_SUCCESS";
export const DELETE_TRAINEE_FAILURE = "DELETE_TRAINEE_FAILURE";
export const CREATE_TRAINEE_ATTRIBUTE_REQUEST =
  "CREATE_TRAINEE_ATTRIBUTE_REQUEST";
export const CREATE_TRAINEE_ATTRIBUTE_SUCCESS =
  "CREATE_TRAINEE_ATTRIBUTE_SUCCESS";
export const CREATE_TRAINEE_ATTRIBUTE_FAILURE =
  "CREATE_TRAINEE_ATTRIBUTE_FAILURE";
export const GET_CYCLES_ERROR = "GET_CYCLES_ERROR";
export const GET_LOGGED_USER = "GET_LOGGED_USER";

export const CREATE_TICKET = "CREATE_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const GET_USER_TICKETS = "GET_USER_TICKETS";
export const GET_ALL_TICKETS = "GET_ALL_TICKETS";
export const GET_TICKET = "GET_TICKET";
export const RESOLVE_TICKET = "RESOLVE_TICKET";
export const GET_ALL_FILTERED_TICKETS = "GET_ALL_FILTERED_TICKETS";
export const GET_ALL_TRAINEES = "GET_ALL_TRAINEES";
export const GET_ALL_TRAINEES_ERROR = "GET_ALL_TRAINEES_ERROR";
export const ADD_TRAINEE_IN_COHORT = "ADD_TRAINEE_IN_COHORT";
export const ADD_TRAINEE_IN_COHORT_ERROR = "ADD_TRAINEE_IN_COHORT_ERROR";
export const FETCH_BLOGS_LOADING = "FETCH_BLOGS_LOADING";
export const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
export const FETCH_BLOGS_FAIL = "FETCH_BLOGS_FAIL";
export const FETCH_USER_BLOGS_LOADING = "FETCH_USER_BLOGS_LOADING";
export const FETCH_USER_BLOGS_SUCCESS = "FETCH_USER_BLOGS_SUCCESS";
export const FETCH_USER_BLOGS_FAIL = "FETCH_USER_BLOGS_FAIL";
export const FETCH_SINGLE_BLOG_LOADING = "FETCH_SINGLE_BLOG_LOADING";
export const FETCH_SINGLE_BLOG_SUCCESS = "FETCH_SINGLE_BLOG_SUCCESS";
export const FETCH_SINGLE_BLOG_FAIL = "FETCH_SINGLE_BLOG_FAIL";

export const FETCH_COMMENTS_LOADING = "FETCH_COMMENTS_LOADING";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";
export const FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL";

export const CREATE_COMMENT_LOADING = "CREATE_COMMENT_LOADING";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const UPDATE_COMMENT_LOADING = "UPDATE_COMMENT_LOADING";
export const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS";
export const UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL";

export const DELETE_COMMENT_LOADING = "DELETE_COMMENT_LOADING";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const COUNT_COMMENTS_LOADING = "COUNT_COMMENTS_LOADING";
export const COUNT_COMMENTS_SUCCESS = "COUNT_COMMENTS_SUCCESS";
export const COUNT_COMMENTS_FAIL = "COUNT_COMMENTS_FAIL";

export const ADD_COMMENT_LIKE_LOADING = "ADD_COMMENT_LIKE_LOADING";
export const ADD_COMMENT_LIKE_SUCCESS = "ADD_COMMENT_LIKE_SUCCESS";
export const ADD_COMMENT_LIKE_FAIL = "ADD_COMMENT_LIKE_FAIL";

export const GET_COMMENT_LIKES_LOADING = "GET_COMMENT_LIKES_LOADING";
export const GET_COMMENT_LIKES_SUCCESS = "GET_COMMENT_LIKES_SUCCESS";
export const GET_COMMENT_LIKES_FAIL = "GET_COMMENT_LIKES_FAIL";

export const FETCH_REPLIES_LOADING = "FETCH_REPLIES_LOADING";
export const FETCH_REPLIES_SUCCESS = "FETCH_REPLIES_SUCCESS";
export const FETCH_REPLIES_FAIL = "FETCH_REPLIES_FAIL";

export const ADD_REPLY_LOADING = "ADD_REPLY_LOADING";
export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";
export const ADD_REPLY_FAIL = "ADD_REPLY_FAIL";
