export enum fetchBlogs {
  FETCH_BLOGS_LOADING = "FETCH_BLOGS_LOADING",
  FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS",
  FETCH_BLOGS_FAIL = "FETCH_BLOGS_FAIL",
}

export enum fetchSingleBlog {
  FETCH_SINGLE_BLOG_LOADING = "FETCH_SINGLE_BLOG_LOADING",
  FETCH_SINGLE_BLOG_SUCCESS = "FETCH_SINGLE_BLOG_SUCCESS",
  FETCH_SINGLE_BLOG_FAIL = "FETCH_SINGLE_BLOG_FAIL",
}

export enum createBlog {
  CREATE_BLOG_LOADING = "CREATE_BLOG_LOADING",
  CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL",
}

export enum updateBlog {
  UPDATE_BLOG_LOADING = "UPDATE_BLOG_LOADING",
  UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL",
}

export enum deleteBlog {
  DELETE_BLOG_LOADING = "DELETE_BLOG_LOADING",
  DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL",
}

export enum hideBlog {
  HIDE_BLOG_LOADING = "HIDE_BLOG_LOADING",
  HIDE_BLOG_SUCCESS = "HIDE_BLOG_SUCCESS",
  HIDE_BLOG_FAIL = "HIDE_BLOG_FAIL",
}
