export enum fetchComments {
    FETCH_COMMENTS_LOADING = "FETCH_COMMENTS_LOADING",
    FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS",
    FETCH_COMMENTS_FAIL = "FETCH_COMMENTS_FAIL",
  }
  
  export enum createComment {
    CREATE_COMMENT_LOADING = "CREATE_COMMENT_LOADING",
    CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS",
    CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL",
  }
  
  export enum updateComment {
    UPDATE_COMMENT_LOADING = "UPDATE_COMMENT_LOADING",
    UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS",
    UPDATE_COMMENT_FAIL = "UPDATE_COMMENT_FAIL",
  }
  
  export enum deleteComment {
    DELETE_COMMENT_LOADING = "DELETE_COMMENT_LOADING",
    DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL",
  }
  