export enum fetchReactions {
    FETCH_REACTIONS_LOADING = "FETCH_REACTIONS_LOADING",
    FETCH_REACTIONS_SUCCESS = "FETCH_REACTIONS_SUCCESS",
    FETCH_REACTIONS_FAILURE = "FETCH_REACTIONS_FAILURE",
  }
  
  export enum addReaction {
    ADD_REACTION_LOADING = "ADD_REACTION_LOADING",
    ADD_REACTION_SUCCESS = "ADD_REACTION_SUCCESS",
    ADD_REACTION_FAIL = "ADD_REACTION_FAIL",
  }
  
  export enum removeReaction {
    REMOVE_REACTION_LOADING = "REMOVE_REACTION_LOADING",
    REMOVE_REACTION_SUCCESS = "REMOVE_REACTION_SUCCESS",
    REMOVE_REACTION_FAIL = "REMOVE_REACTION_FAIL",
  }
  